name: Build Snapshot

on:
  push:
    branches:
      - 'development'

jobs:
  ##########################################################################################
  # Module Tests
  ##########################################################################################
  tests:
    secrets: inherit
    uses: ./.github/workflows/tests.yml

  ##########################################################################################
  # Format Source Code
  ##########################################################################################
  format:
    name: Code Auto-Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup CommandBox CLI
        uses: Ortus-Solutions/setup-commandbox@v2.0.1
        with:
          install: commandbox-cfformat
          warmup: true

      - name: Run formatting rules
        run: box run-script format

      - name: Commit Format Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply cfformat changes

  ##########################################################################################
  # Release it
  ##########################################################################################
  release:
    uses: ./.github/workflows/release.yml
    needs: [ tests, format ]
    secrets: inherit
    with:
      snapshot: true
